### ISSUE TITLE
Restricts autocomplete to given number of completions

### ISSUE THREAD

**Issue by misterzenzel** [cmsc22000-project-2018/autocomplete#61]

**Comment by dayaffe** [comment]
The default restriction was set to 10. ./autocomplete can now take an additional flag for autocomplete mode:
./autocomplete -i -d <dictionary> <restriction>

In the GUI, there is now a display of how many completions are showing out of the potential if it is not all of them.

Note: I had a segfault as well as a logic error that took awhile to debug. The segfault ended up being a result of calling args[3] when in the default case that would blow up the program because I was reaching into unallocated memory. The logic error was a result of num_children being used later in the script from code generated by someone else. I changed num_children to the generalized variable I created which calculates how many completions will be shown.
